// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemcutikaryawan.Data;

#nullable disable

namespace sistemcutikaryawan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("sistemcutikaryawan.Models.Cuti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alasan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaKaryawan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cutis");
                });
#pragma warning restore 612, 618
        }
    }
}
